#!/usr/bin/env bun
// Runs ON a box (pushed to ~/.cnc/bin/bw-sync.ts by `cnc secrets`).
// Renders ~/workspace/<org>/.env from ~/.cnc/bw/<org>.yml using the on-box master
// password in ~/.cnc/bw/<org>.secret. No secret ever leaves the box; .env is chmod 600.
//
//   bun ~/.cnc/bin/bw-sync.ts <org>
import { readFileSync, writeFileSync, existsSync, chmodSync, mkdirSync } from "node:fs";
import { homedir } from "node:os";
import { join, dirname } from "node:path";

const org = process.argv[2];
if (!org) { console.error("usage: bw-sync <org>"); process.exit(1); }

const HOME = homedir();
const cfgPath = join(HOME, ".cnc", "bw", `${org}.yml`);
const secretPath = join(HOME, ".cnc", "bw", `${org}.secret`);
if (!existsSync(cfgPath)) { console.error(`missing ${cfgPath} — run: cnc secrets <team>`); process.exit(1); }
if (!existsSync(secretPath)) { console.error(`missing ${secretPath} — set it: cnc secrets <team> --set-password ${org}`); process.exit(1); }

const cfg = Bun.YAML.parse(readFileSync(cfgPath, "utf8")) as {
  server: string; account: string;
  items?: Record<string, { item: string; field?: string }>;
};

// Parse the on-box secret file: KEY='value' lines (BW_PASSWORD required; API key optional).
const secret: Record<string, string> = {};
for (const line of readFileSync(secretPath, "utf8").split("\n")) {
  if (/^\s*#/.test(line)) continue;
  const m = line.match(/^\s*(\w+)\s*=\s*['"]?(.*?)['"]?\s*$/);
  if (m) secret[m[1]] = m[2];
}
if (!secret.BW_PASSWORD) { console.error("BW_PASSWORD missing in secret file"); process.exit(1); }

// Per-org data dir so several org vaults (different Vaultwarden servers) can be logged in
// side by side on one box — the main controller holds them all.
const dataDir = join(HOME, ".cnc", "bw", `${org}.data`);
mkdirSync(dataDir, { recursive: true });
const baseEnv: Record<string, string> = {
  ...process.env as Record<string, string>,
  PATH: `${join(HOME, ".local", "bin")}:${process.env.PATH ?? ""}`,
  BITWARDENCLI_APPDATA_DIR: dataDir,
  BW_PASSWORD: secret.BW_PASSWORD,
  ...(secret.BW_CLIENTID ? { BW_CLIENTID: secret.BW_CLIENTID, BW_CLIENTSECRET: secret.BW_CLIENTSECRET ?? "" } : {}),
};

async function bw(args: string[], extra: Record<string, string> = {}) {
  const p = Bun.spawn(["bw", ...args], { env: { ...baseEnv, ...extra }, stdout: "pipe", stderr: "pipe" });
  const [out, err, code] = await Promise.all([
    new Response(p.stdout).text(), new Response(p.stderr).text(), p.exited,
  ]);
  return { code, out: out.trim(), err: err.trim() };
}

// Point the CLI at this org's server (a box handles one org/server at a time).
await bw(["config", "server", cfg.server]);

// Login if needed (API key preferred; else email + master password).
if ((await bw(["login", "--check"])).code !== 0) {
  const login = secret.BW_CLIENTID
    ? await bw(["login", "--apikey"])
    : await bw(["login", cfg.account, "--passwordenv", "BW_PASSWORD"]);
  if (login.code !== 0) { console.error("bw login failed:\n" + (login.err || login.out)); process.exit(1); }
}

// Unlock -> session, then sync the vault.
const unlock = await bw(["unlock", "--passwordenv", "BW_PASSWORD", "--raw"]);
if (unlock.code !== 0) { console.error("bw unlock failed:\n" + (unlock.err || unlock.out)); process.exit(1); }
const session = unlock.out;
await bw(["sync"], { BW_SESSION: session });

// Fetch each mapped item; missing items are warned + skipped, not fatal.
const items = cfg.items ?? {};
const lines = [`# generated by bw-sync for ${org} — DO NOT COMMIT. on-box only.`];
let ok = 0, miss = 0;
for (const [envVar, spec] of Object.entries(items)) {
  const field = spec.field ?? "password";
  const r = await bw(["get", field, spec.item], { BW_SESSION: session });
  if (r.code === 0 && r.out) { lines.push(`${envVar}=${r.out}`); ok++; }
  else { console.error(`  ! ${envVar}: "${spec.item}" (${field}) not found — skipped`); lines.push(`# ${envVar}=  (missing in vault: ${spec.item})`); miss++; }
}

const workspace = process.env.WORKSPACE || join(HOME, "workspace");
const outPath = join(workspace, org, ".env");
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, lines.join("\n") + "\n", { mode: 0o600 });
chmodSync(outPath, 0o600);
console.log(`wrote ${outPath}  (${ok} secrets, ${miss} missing)`);
